name: CI/CD Pipeline to AWS with Docker Hub

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  Checkout:
    name: Checkout to github and docker
    runs-on: ubuntu-latest 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  build-and-push:
    needs: Checkout
    name: Builds and push to docker
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: chrystjr2/chatbackend
      IMAGE_TAG: dev-${{ github.run_number }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  Clone-and-update-argocdrepo:
    needs: build-and-push
    name: Clone and update argocdrepo
    runs-on: ubuntu-latest
    steps:
      - name: Clone ArgoCD repository
        uses: actions/checkout@v3
        with:
          repository: rentdevops/argocd 
          token: ${{ secrets.CHECKOUT_TOKEN }}  
          path: chatnode
          # ref: v2

      - name: List files in the current directory
        run: |
          ls -la chatnode
      - name: Update ArgoCD deployment.yaml
        run: |
          sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|g" chatnode/chatnode/backend.yaml
      - name: Commit and push changes to ArgoCD repo
        run: |
          cd chatnode
          git config --global user.email "chriscrsov@gmail.com"
          git config --global user.name "chrystjr"
          git add chatnode/backend.yaml  
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
